kind: Service                             
apiVersion: v1
metadata:
  name: kubeproject
  labels:
    app: kubeproject
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kubeproject                    
  type: LoadBalancer     
